### ISSUE TITLE
Cursor doesn't focus on terminal window when tests have run

### ISSUE THREAD

**Issue by olimorris** [calebporzio/better-phpunit#19]
Hi Caleb,

Firstly a tip of the hat for this marvellous extension.

Using VSCode 1.18.1 on macOS 10.13.1, I notice when I run the tests through Better-PHPUnit, and they run successfully, my cursor is not focused on the terminal window at the bottom of my screen. That mean it's an extra couple of key strokes to close it, when in theory if I was focussed in the terminal, I could press any key.

There doesn't appear to be a setting in VSCode for this so I wondered if this is something to do with the Extension itself?

Thanks,

Oli

**Comment by wilburpowery** [comment]
You can toggle the integrated terminal. control + `
<img width="748" alt="screen shot 2017-11-27 at 11 19 52 am" src="https://user-images.githubusercontent.com/15817188/33279665-fe5a7ac4-d364-11e7-945e-787142500bfc.png">
Works very good for me.

**Comment by olimorris** [comment]
@wilburpowery sure you can. But that doesn't address the issue

**Comment by wilburpowery** [comment]
I'll look into focusing the cursor in the terminal window. If I find anything, I'll PR it.

**Comment by calebporzio** [comment]
![image](https://user-images.githubusercontent.com/3670578/33493278-86ccb8d8-d68d-11e7-99d6-4b7e630e7ade.png)

I tried executing the focus terminal command after running the task, but it doesn't really work. I agree this would be nice, or like a config option to auto close if the test passes? idk, I like the idea, would still want a config option for it because I imagine some people want to keep typing while the test is running and not have to click back on the editor.

**Comment by olimorris** [comment]
@calebporzio yep completely agree on all points. As long as they could be configured by the user then they would all be brilliant additions.

I just feel the extra click I have to make to shit focus to the terminal and scroll the failure message or to simply close the terminal (that's two button presses) is a tad annoying...Annoying being the key word...Not heart breaking or anything.

**Comment by calebporzio** [comment]
I don't see a way to do this at the moment - closing for now
