### ISSUE TITLE
Tests output not colorized

### ISSUE THREAD

**Issue by JonathanNasc** [calebporzio/better-phpunit#22]
Hello, first of all thank you for this brilliant extension.

Something happen in this last week and the tests output is not colorized anymore.
Have you seen this before?

I'm using:
- Mac OS Sierra 10.12.6
- Visual Studio Code 1.18.1
- Better PHPUnit 0.3.5

**Comment by calebporzio** [comment]
This is hilarious (and super lucky): all my versions match yours exactly.

I'm still getting colors.

Try copying the command that get's run exactly, pasting it into the terminal and seeing what happens.

Make sure your phpunit.xml file has "colors=true"

**Comment by JonathanNasc** [comment]
Very strange, when I run the command directly by terminal the output is colorized.

**Comment by calebporzio** [comment]
Hmm... I'd like to help you, but I don't really know the next step if our environments are exactly the same and you are getting different behavior. Any ideas? Or other things you could try? try it with a different project? try it with a different phpunit binary

**Comment by calebporzio** [comment]
Closing this for now - let me know if you find anything.

**Comment by petercoles** [comment]
I had a problem with exactly the same symptoms. Running the command with the plugin wasn't colorized, but run the same command directly in the terminal and it was. Initially I got around this by by adding the --colors suffice.

Sadly it's now clear that the problem was a bit deeper, specifically that the phpunit settings aren't being picked up, or are being ignored. This is a bit of problem as it prevents switching to a sqlite database for unit testing.

Any thoughts, or further information that I could provide to help diagnose this?

**Comment by sunscreem** [comment]
@calebporzio I'm still having this issue. I've tried adding `"better-phpunit.commandSuffix": "--colors"` to my user settings. I've also ensured that my phpunit.xml `colors="true"` is there. 

Windows 10
Visual Studio Code 1.19.1
Better PHPUnit 0.5.3

**Comment by calebporzio** [comment]
@sunscreem - take a look at #30 and see if your problem is resolved - thanks!

**Comment by SimonJ** [comment]
Did you get this working @petercoles :)?
