### ISSUE TITLE
Running tests over ssh doesn't read values from phpunit.xml file

### ISSUE THREAD

**Issue by jcergolj** [calebporzio/better-phpunit#68]
I am having a Homestead instance and I would like to run tests over ssh. For some reason, the environment doesn't switch to `test` and environment variables form phpunit.xml file are not read.

**Comment by 8kiwi8** [comment]
I also facing the same issue when using laradock. I need to ssh into docker instance to run my test.

Since the phpunit.xml is in the root directory, it simply ignore the configuration setting like below.

`> Executing task: ssh -i ../laradock/workspace/insecure_id_rsa -R9000:127.0.0.1:9000 -tt -p2222 root@192.168.99.100 "/var/www/feedme-restaurant-web/vendor/bin/phpunit /var/www/feedme-restaurant-web/tests/Feature/ExampleTest.php --filter '^.*::testBasicTest$'" <`

If the default login path does not point to the root directory of the project, it'll ignore the phpunit.xml.

It'll be better when runnning test over ssh, provide the absolute path to the configuration file, or append a "cd" to project directory in-front of the command.

**Comment by vasilestefirta** [comment]
@jcergolj This [solution](https://github.com/calebporzio/better-phpunit/issues/32#issuecomment-380399826) worked for me 👍
