### ISSUE TITLE
test result is not correct when the method is written in non-alphabetic languages

### ISSUE THREAD

**Issue by jdssem** [calebporzio/better-phpunit#93]
## What are the steps to reproduce this issue?

1. write a test in Korean like below.
```
/** @test */
public function 한글로_테스트_메서드를_작성할_때()
{
    $this->assertTrue(false);
}
```

2. run the test on the method above.
```
PHPUnit 7.5.6 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 404 ms, Memory: 14.00 MB

OK (1 test, 1 assertion)
```

## What were you expecting to happen?
The test above should be failed but it's green whatever assertions are.

When I run a test on the class name or run suite, it is just fine. It shows the error like below.
```
PHPUnit 7.5.6 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 199 ms, Memory: 14.00 MB

There was 1 failure:

1) Tests\Unit\ExampleTest::한글로_테스트_메서드를_작성할_때
Failed asserting that false is true.

/Users/jdssem/code/cerveau/tests/Unit/ExampleTest.php:22

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

## What versions are you using?
**Operating System:** macOS Mojave
**Package Version:** 1.3.3

**Comment by calebporzio** [comment]
I could not reproduce this error. Because you are getting normal PHPUnit output, it feels like the Korean characters might not be the issue - but I'm not totally sure. Thanks for providing good steps to reproduce, but I can't seem to find anything for you. Maybe run through some sanity checks and make sure it's nothing on your end?

![image](https://user-images.githubusercontent.com/3670578/53748329-24bc6b80-3e73-11e9-95f4-2492844ae9cf.png)

**Comment by jdssem** [comment]
Thanks for your reply. I made this test in my Laravel project. That may be a problem.

**Comment by danilopolani** [comment]
Hello @jdssem 
I've just tried in a laravel project (5.7) and it works fine, the problem is that your PHPUnit "fails": it says the test is fine but it is not and, if the test is OK, it does not show the method name.

To "bypass" this behaviour, try put this line in your VSCode preferences:

```
"better-phpunit.commandSuffix": "--testdox"
```

Now if you run again your test, it will display the method name, so you can check it.

**Comment by jdssem** [comment]
Thanks @danilopolani . I've just tested again and now it will return 'fail'. I don't know why it works now but I think this is not the issue anymore.

**Comment by danilopolani** [comment]
@jdssem don't worry, I'm happy now it works :)
